### PR TITLE
Sending notifications when jobs fail.

### PR DESCRIPTION
**Pull request by iannbing**
## Description

This PR exposes the BE functionality of sending notifications to desired channels (e.g. Slack) when jobs fail.

Closes: #120 

## Todo

- [x] Items from https://github.com/orchest/orchest/pull/1008#issuecomment-1143731359

## Checklist

- [x] The documentation reflects the changes.
- [x] The PR branch is set up to merge into `dev` instead of `master`.
- [x] In case I changed one of the services’ `models.py` I have performed the appropriate database
      migrations (refer to `scripts/migration_manager.sh`).
- [x] In case I changed code in the `orchest-sdk` I followed its [release
      checklist](https://github.com/orchest/orchest/blob/master/orchest-sdk/python/RELEASE-CHECKLIST.md)
- [x] In case I changed code in the `orchest-cli` I followed its [release
      checklist](https://github.com/orchest/orchest/blob/master/orchest-cli/RELEASE-CHECKLIST.md)
- [x] I haven't introduced breaking changes that would disrupt existing jobs, i.e. backwards
      compatibility is maintained.
- [x] In case I changed the dependencies in any `requirements.in` I have run `pip-compile` to update
      the corresponding `requirements.txt`.

### CODE REVIEW

**Comment by fruttasecca** [comment]
Currently, we are subscribing users to 
```
 project:one-off-job:failed
 project:cron-job:run:failed
 ```
 A one off job is registered as failed after all its pipeline runs have entered an end state, and there is at least 1 failed run.
 A cron job is registered as failed only if, pretty much, fails to enter the `STARTED` state, which is something that happens after "confirming" the job from a draft.
 
 We might want to subscribe users to the following events (along with the previous two): 
 - `project:one-off-job:pipeline-run:failed`: a pipeline run of a job has failed, note that it implies that, if there are many runs that fail, many notifications will be delivered
 - `project:cron-job:run:failed`: a cron job run is a batch of pipeline runs created based on the cron job schedule. This event can be triggered in two different moments: if the BE is not able to queue the batch of pipeline runs, or if a pipeline run part of the batch fails
- `project:cron-job:run:pipeline-run:failed`: a pipeline run has failed, note that it implies that, if there are many runs that fail, many notifications will be delivered

**Comment by fruttasecca** [comment]
I am not entirely sure showing events in this raw form
image

**Comment by fruttasecca** [comment]
About the webhook docs, which should probably decide who's doing what

**Comment by iannbing** [comment]
> Given the design, what happens if we have existing users with existing webhooks, and we decide to change what events we are subscribing users to by default? I think it implies either that we need to update existing webhooks in the database or that the view will have to change to accommodate for the fact that different webhooks might be subscribed to different events?

If you meant users who are already using the endpoints without GUI, indeed it's then not correctly presented in the UI. 

I think, though, we have to allow user to select the events to subscribe before changing any default event types (then we could show a toggle per event).

And also, the list of webhooks in Notification settings would be app-wide, meaning that its `subscriptions` would be empty. We have to think about how to allow user subscribe to jobs with a specific UUID.

**Comment by yannickperrenet** [comment]
> A one off job is registered as failed after all its pipeline runs have entered an end state, and there is at least 1 failed run.
A cron job is registered as failed only if, pretty much, fails to enter the STARTED state, which is something that happens after "confirming" the job from a draft.

I would argue that users are interested in getting notified whenever a pipeline run fails. Reasoning about the failure of an encapsulating one-off job or cronjob (meaning that it has many pipeline runs due to parameters) I don't think makes much sense. I would want to get a notification the moment something fails so that I can expect it and fix things. 

Let's say you have two pipeline runs X and Y as part of a job, then X and Y could run the same code but on different data sources. In that case it is very important that both X and Y run, so the moment one fails we should notify the user.

> `project:cron-job:run:pipeline-run:failed`: a pipeline run has failed, note that it implies that, if there are many runs that fail, many notifications will be delivered

This I like ^_^. We could later add an option where you can limit the number of notifications per job, if that is what users want.

> I am not entirely sure showing events in this raw form

I totally agree. I would rather give them more appropriate names.

**Comment by yannickperrenet** [comment]
### Overview of nitpicks/issues I encountered

#### 1. Alignment is of banner is off

The text in the banner (in the jobs list view) is not vertically aligned in the center. Left side is too high and right side is too low.

image

#### 2. Alternative text proposal for notification settings

I would change the text to: "Get notified about specific events in Orchest." The fact that we use webhooks is something they can see in the actual settings themselves.

image

#### 3. Unclear "error" indication when testing webhook

I used https://webhook.site/ to quickly test out the _TEST_ button when creating a webhook. The payload got successfully POST'ed but in our UI we show an :exclamation:. Not sure how to interpret it.

image

#### 4. Icon alignment in webhooks table is off

After clicking the _TEST_ in the Connection column I felt like the :white_check_mark: was not aligned properly (vertically speaking).

image

#### 5. Connection column in webhooks table

In the above screenshot you can see that we offer a _TEST_ functionality in the webhooks table. When I first saw this I immediately thought: "Why doesn't Orchest check it for me? Why do I have to press that button?" 

In addition, after I pressed _TEST_ and added another webhook the :white_check_mark: from the first test disappeared. 

#### 6. Unclear / Unconfigurable webhook events vs channels

From the UI it seems like every webhook will be subscribed to all events. I don't think this is a common use case though, I would expect different channels (if more than 1 at all) to be subscribed to different events. Why don't we allow what events a webhook channel is subscribed to? Moreover, then the channel should also show the events it is subscribed to.
image

#### 7. Can't edit existing webhook 

In the above screenshot you can see the table listing the webhook channels. How can I edit an existing webhook? I tried clicking on the row in the table but that didn't work. I would have liked to add a name.

**Comment by iannbing** [comment]
@yannickperrenet 

> The text in the banner (in the jobs list view) is not vertically aligned in the center. Left side is too high and right side is too low.

> I would change the text to: "Get notified about specific events in Orchest." The fact that we use webhooks is something they can see in the actual settings themselves.

Changed accordingly.

> I used https://webhook.site/ to quickly test out the TEST button when creating a webhook. The payload got successfully POST'ed but in our UI we show an ❗. Not sure how to interpret it.

You probably were testing an older commit. @fruttasecca helped out with a new endpoint a bit later. I just tested with `https://webhook.site/` and it works.

> After clicking the TEST in the Connection column I felt like the ✅ was not aligned properly (vertically speaking).

Could you share which browser you're using? I couldn't reproduce it on Safari, Chrome, and Brave on Mac. 

> In the above screenshot you can see that we offer a TEST functionality in the webhooks table. When I first saw this I immediately thought: "Why doesn't Orchest check it for me? Why do I have to press that button?"

Note that this "test" is a POST request that sends an actual notification, not a silent GET health check. It'd be better letting user fire it for testing instead of firing unsolicited notifications every time this view is rendered.

> From the UI it seems like every webhook will be subscribed to all events. I don't think this is a common use case though, I would expect different channels (if more than 1 at all) to be subscribed to different events. Why don't we allow what events a webhook channel is subscribed to? Moreover, then the channel should also show the events it is subscribed to.

> In the above screenshot you can see the table listing the webhook channels. How can I edit an existing webhook? I tried clicking on the row in the table but that didn't work. I would have liked to add a name.

AFAIK the agreed scope of this PR is a MVP: send notifications when job runs fail. I think the said scenarios are 100% valid, but design and endpoints are not yet in place (POST, GET, but no PUT).

**Comment by iannbing** [comment]
> In addition, after I pressed TEST and added another webhook the ✅ from the first test disappeared.

Fixed 🙂

**Comment by yannickperrenet** [comment]
Would it make sense to change the `Events` title in the notifications settings to `Subscribed events`? 

To me `Events` feels like a list of all possible events and not perse "events that I subscribed to". Given that the dialog for setting up a webhook doesn't allow for configuration of events, I think we should make clear that all events are automatically subscribed to.

**Comment by ncspost** [comment]
> Would it make sense to change the Events title in the notifications settings to Subscribed events?

It makes more sense when the table headings + switches are there...

CleanShot 2022-06-01 at 17 01 48@2x

These switches can appear disabled for the MVP

**Comment by ncspost** [comment]
CleanShot 2022-06-01 at 17 19 47@2x

It might be cleaner to structure events like this

**Comment by fruttasecca** [comment]
Setting an invalid URL is not handled correctly, as a user I am allowed to save it, the request will fail and the FE will show an entry regardles.

**Comment by iannbing** [comment]
> Setting an invalid URL is not handled correctly, as a user I am allowed to save it, the POST request to the BE will fail and the FE will show an entry regardless.

I intentionally made it so. Orchest could not be hold responsible for ensuring the receiver service is active. Even if the TEST is passing while user is creating a webhook in the dialog, the integration could still fail anytime.

**Review by BrunoOrchest — APPROVED** [review]

**Review by fruttasecca — APPROVED** [review]
lgtm :+1:

**Comment by iannbing** [comment]
@ncspost 
I've addressed your feedback as much as possible. Some questions about the remainders:

- Why do we need to capticalize webhook? I think it's a common noun, not something like "Internet". See [wekipedia](https://en.wikipedia.org/wiki/Webhook) for example.
- I couldn't reproduce the functionality failures that you encountered. Could you deploy the latest commit and try again? It could be that you were testing on an old commit 🙂

**Comment by ncspost** [comment]
CleanShot 2022-06-06 at 14 20 42@2x

Switches should be off and disabled until a webhook is created

**Comment by iannbing** [comment]
> Switches should be off and disabled until a webhook is created

Fixed.

**Review by ncspost — APPROVED** [review]
LGTM! Great work ⭐

**Review by yannickperrenet — APPROVED** [review]
Super sick! I love it :1st_place_medal:

**Pull request merged**
