### PR TITLE
Upgrade JupyterLab to `v3.4`

### PR DESCRIPTION
**Pull request by astrojuanlu**
[Release announcement](https://discourse.jupyter.org/t/jupyterlab-3-4-0-is-released/14106?u=astrojuanlu), [complete changelog](https://github.com/jupyterlab/jupyterlab/releases/tag/v3.4.0).

Personal highlights:

New cell toolbar

cell-toolbar

"New tab" button

new-tab

### CODE REVIEW

**Comment by ricklamers** [comment]
Did you do some testing? 😎

**Comment by astrojuanlu** [comment]
I tested:

- The functionalities advertised above ✔️ 
- Cell tags ✔️ 
- Double-click goes to file ✔️ 
- ...even if the file was originally closed ✔️ 
- Run step ✔️ 
- Stop session, start session, wait for session started, double click launches JupyterLab  ✔️
- Stop session, double click launches JupyterLab ⚠️ _sometimes_ it gets stuck, sometimes it works (but I think this is happening with the previous version as well)

**Comment by astrojuanlu** [comment]
Exceptionally I did a rebase, since there was a massive merge to `dev`, this has only 1 commit, and nobody other than myself interacted with this branch.

**Comment by astrojuanlu** [comment]
Tested again on top of current `dev`. Everything seems to work, although there's still some flakiness when it comes to stop/start and getting into JupyterLab, sometimes it will get stuck and a browser refresh or two will fix it. Not sure if it's due to 3.4.0 though.

**Comment by astrojuanlu** [comment]
There it goes :shipit:

**Pull request merged**
