### PR TITLE
Functional Component Transformation (Part 1)

### PR DESCRIPTION
**Pull request by joe-bell**
## Description

Further transformation associated to #259 

**Current progress**

- [ ] `/components` – 20/32 (**+4**)
- [ ] `/jupyter` – 0/1 – _low priority_
- [ ] `/utils` – 4/5 – _`webserver-utils` low priority_
- [ ] `/views` – 14/19 (**+4**)
- [x] `App.jsx`
- [x] `main.jsx`

### Checklist

- [x] The documentation reflects the changes.
- [ ] I have manually tested the application to make sure the changes don’t cause any downstream issues, which includes making sure `./orchest status --ext` is not reporting failures when Orchest is running.
- [ ] In case I changed code in the `orchest-sdk`, I updated its version according to [SemVer](https://semver.org/) in its `_version.py` and updated the version compability table in its `README.md`

- [ ] In case I changed one of the services’ `models.py` I have performed the appropriate database migrations.

### CODE REVIEW

**Comment by joe-bell** [comment]
⚠️ **DO NOT MERGE: `FilePicker` has not been tested**

**Comment by joe-bell** [comment]
**DO NOT MERGE –  `ConfigureJupyterLabView` is untested** ⚠️ 

Having troubles running locally after changing branches

**Comment by joe-bell** [comment]
⚠️ **DO NOT MERGE** - There is a crucial bug with `unsavedChanges` that needs to be addressed as a priority

**Comment by ricklamers** [comment]
LGTM! Well done on the transform to functional components.

**Review by ricklamers — APPROVED** [review]

**Pull request merged**
