### PR TITLE
Onboarding

### PR DESCRIPTION
**Pull request by joe-bell**
## Description

- [x] Add `Layout` component and wrap all `View` components with it (hence the many file changes 🥴)
    - In a later PR this will also handle wrapping pages with `Header`/`Sidebar` etc.
    - For now, it will handle displaying the "onboarding" dialog on any page for a "new" user.
- [x] Add `OnboardingDialog` (used **inside** `Layout`) to show CLOUD users on first load (using local storage) 
- [x] Cleanup `ServiceTemplatesDialog` to align with others.

### Demo

https://user-images.githubusercontent.com/7349341/122558935-514a2080-d047-11eb-8f3d-0bfcaa2220a6.mp4

### How to Test

Because we're only showing this Dialog to `CLOUD` users on first load, here's what you can do to debug/recreate locally…

1. Override the config in `services/orchest-webserver/client/src/main.tsx`
    ```diff
       <DesignSystemProvider>
    --   <OrchestProvider {...config}>
    ++   <OrchestProvider config={{ ...config.config, CLOUD: true }} user_config={config.user_config}>
           <App />
         </OrchestProvider>
       </DesignSystemProvider>
    ```
2. Clear your local storage (after each "close", a key will be set to state that onboarding has been completed)

### Checklist

- [x] The documentation reflects the changes.
- [x] I have manually tested the application to make sure the changes don’t cause any downstream issues, which includes making sure `./orchest status --ext` is not reporting failures when Orchest is running.
- [ ] In case I changed code in the `orchest-sdk`, I updated its version according to [SemVer](https://semver.org/) in its `_version.py` and updated the version compability table in its `README.md`

- [ ] In case I changed one of the services’ `models.py` I have performed the appropriate database migrations.

### CODE REVIEW

**Review by yannickperrenet — APPROVED** [review]
LGTM! Really like the dialog.

Haven't looked at the code though, but the end results is looking fresh ;)

**Comment by yannickperrenet** [comment]
@joe-bell Can we merge this into `dev` instead of `master`?

**Comment by joe-bell** [comment]
**Update**: Added indicator dots based on feedback

Screenshot 2021-06-21 at 12 38 23

**Comment by joe-bell** [comment]
@ricklamers all change requests have been made!

**Review by ricklamers — APPROVED** [review]

**Comment by ricklamers** [comment]
Fantastic job @joe-bell glad with the end result.

As per discussion, we'll later replace the fixed height for a dynamic (tallest component height) solution.

**Pull request merged**
