### PR TITLE
Release `v2022.07.6`

### PR DESCRIPTION
**Pull request by yannickperrenet**
## Description

New Orchest release: `v2022.07.6`

To mitigate performance issues (mainly noticeable on Windows) we are now no longer using `eventlet` for the Flask services and instead use `gunicorn` + `gthread` (which uses [`futures.ThreadPoolExecutor`](https://docs.python.org/3/library/concurrent.futures.html#concurrent.futures.ThreadPoolExecutor) under the hood) :fire: 

## Checklist

- [x] I have manually tested my changes and I am happy with the result.
- [x] The documentation reflects the changes.
- [x] I haven't introduced breaking changes that would disrupt existing jobs, i.e. backwards compatibility is maintained.
- [x] In case I changed the dependencies in any `requirements.in` I have run `pip-compile` to update the corresponding `requirements.txt`.
- [x] In case I changed one of the services' `models.py` I have performed the appropriate database migrations (refer to the [DB migration docs](https://docs.orchest.io/en/stable/development/development_workflow.html#database-schema-migrations)).
- [x] In case I changed code in the `orchest-sdk` I followed its [release checklist](https://github.com/orchest/orchest/blob/master/orchest-sdk/python/RELEASE-CHECKLIST.md).
- [x] In case I changed code in the `orchest-cli` I followed its [release checklist](https://github.com/orchest/orchest/blob/master/orchest-cli/RELEASE-CHECKLIST.md).

### CODE REVIEW

**Comment by ricklamers** [comment]
```Error response from daemon: Get "https://10.106.93.132/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded whi ││ le awaiting headers)                                                                                                                              ││ Stream closed EOF for orchest/kernel-root-7a3a3e92-e0d9-4552-9773-ce8a8d0a790c (image-puller)```


```
HTTP 599: Unknown (Error attempting to connect to Gateway server url 'http://jupyter-eg-2d5bc7ee-44e1-42113259e63b-226f-4d42:8888/jupyter-server-2d5bc7ee-44e1-42113259e63b-226f-4d42'.  Ensure gateway url is valid and the Gateway instance is running.)```

@nhaghighat I'm running into this issue. Is this related to #1150?

@yannickperrenet not releasing today given this issue.

**Comment by yannickperrenet** [comment]
https://github.com/orchest/orchest/pull/1151#issuecomment-1194493763 seems to be related to https://github.com/orchest/orchest/pull/1150, right?

**Comment by fruttasecca** [comment]
@ricklamers I am unable to reproduce the issue, are you getting this in WSL?

**Comment by alexsanderp** [comment]
When will it be released?

**Comment by ricklamers** [comment]
Hi @alexsanderp we’re expecting to release today. Wrapping up some details around certificate use and image pulling that caused an issue in certain k8s environments (including EKS).

**Pull request merged**
