### PR TITLE
Fix web server request logging in dev mode

### PR DESCRIPTION
**Pull request by jerdna-regeiz**
Same problem as fixed in 2edad276dd3e57f9505b490a9fc8331638dc7ce4

It wrongly assumed that there would always be a json, and was apparently
covered by a pre-k8s nginx setting that didn't proxy the requests body.

Fixes: #1086

## Checklist

- [x] I have manually tested my changes and I am happy with the result.
- [x] The documentation reflects the changes.
- [x] The PR branch is set up to merge into `dev` instead of `master`.
- [x] I haven't introduced breaking changes that would disrupt existing jobs, i.e. backwards compatibility is maintained.
- [x] In case I changed the dependencies in any `requirements.in` I have run `pip-compile` to update the corresponding `requirements.txt`.
- [x] In case I changed one of the services' `models.py` I have performed the appropriate database migrations (refer to the [DB migration docs](https://docs.orchest.io/en/stable/development/development_workflow.html#database-schema-migrations)).
- [x] In case I changed code in the `orchest-sdk` I followed its [release checklist](https://github.com/orchest/orchest/blob/master/orchest-sdk/python/RELEASE-CHECKLIST.md).
- [x] In case I changed code in the `orchest-cli` I followed its [release checklist](https://github.com/orchest/orchest/blob/master/orchest-cli/RELEASE-CHECKLIST.md).

### CODE REVIEW

**Comment by fruttasecca** [comment]
Thank you for the quick turnaround :D, don't forget to add yourself to the Orchest contributors :) (at the bottom of the README.md!).

Might I ask you to apply the same patch to the `orchest-api`?

**Comment by jerdna-regeiz** [comment]
> Thank you for the quick turnaround :D, don't forget to add yourself to the Orchest contributors :) (at the bottom of the README.md!), also could you sign the CLA?
> 
> Might I ask you to apply the same patch to the `orchest-api`? (`/services/orchest-api`)

Added myself and signed. I'll gladly do that for `orchest-api` as well, but it might have to wait until later today or tomorrow.

**Comment by fruttasecca** [comment]
Thank you so much for the contribution, we can definitively wait a bit, no rush.

**Comment by yannickperrenet** [comment]
@fruttasecca I guess this PR can be merged now?

And thanks for the contribution @jerdna-regeiz! I didn't want to burden you with these small changes so I made them instead :wink:

**Review by fruttasecca — APPROVED** [review]
lgtm @jerdna-regeiz, thanks again for reporting the issue and opening a PR!

**Pull request merged**
