### PR TITLE
Add mention to conda in the documentation

### PR DESCRIPTION
**Pull request by astrojuanlu**
## Description

Document conda as a supported installer, with its caveats.

Fixes: #759

## Checklist

- [x] The documentation reflects the changes.
- [x] The PR branch is set up to merge into `dev` instead of `master`.
- [x] In case I changed one of the services’ `models.py` I have performed the appropriate database
      migrations (refer to `scripts/migration_manager.sh`).
- [x] In case I changed code in the `orchest-sdk` I followed its [release
      checklist](https://github.com/orchest/orchest/blob/master/orchest-sdk/python/RELEASE-CHECKLIST.md)

### CODE REVIEW

**Comment by astrojuanlu** [comment]
Rendered version: https://orchest--761.org.readthedocs.build/en/761/fundamentals/environments.html#install-packages

**Review by yannickperrenet — APPROVED** [review]
LGTM! :^)

**Comment by astrojuanlu** [comment]
Merging straight away without waiting for the integration tests, as this doesn't change anything in the code (let me know if this is inappropriate)

**Comment by yannickperrenet** [comment]
> Merging straight away without waiting for the integration tests, as this doesn't change anything in the code (let me know if this is inappropriate)

Totally fine. The reason why the integration tests are running is that you make changes to some `Dockerfile`s. Before running the integration tests we do check for file changes as we don't want to run them when its not needed.

https://github.com/orchest/orchest/blob/c6c1199406a48792b35673a5b5a05e4e522d3aab/.github/workflows/integration-tests.yml#L7-L14

**Pull request merged**
