### PR TITLE
make orchest reachable if ORCHEST_FQDN is not defined via cluster ip(…

### PR DESCRIPTION
**Pull request by nhaghighat**
…:port)

## Description

This PR removes the requirement of ORCHEST_FQDN by default, if it is not specified, the cluster will be reachable via ip:port

Fixes: #issue

## Checklist

- [ ] The PR branch is set up to merge into `dev` instead of `master`.

### CODE REVIEW

**Comment by nhaghighat** [comment]
> What would the port be here? 80?

It will be 80 for nginx ingress, just mentioned it for any user who wants to change it.

**Comment by fruttasecca** [comment]
Looks good to me, since there are been some ingress changes in the yaml files, how will this impact users during an update?

**Comment by nhaghighat** [comment]
> Looks good to me, since there are been some ingress changes in the YAML files, how will this impact users during an update?

I haven't tested the update (will do) but theoretically, helm updates the ingress rules, and the Nginx ingress controller will update Nginx, and then Nginx will start to serve the request based on IP address.

**Comment by fruttasecca** [comment]
Alright sounds good. For testing updates, you should be able to do so by rebuilding `orchest-ctl` (with the right tag, i.e. -t <current deployment version> and -o <current deployment version>) and running the `hidden-update ` command.

**Review by fruttasecca — APPROVED** [review]

**Pull request merged**
