### PR TITLE
Hide postgres service

### PR DESCRIPTION
**Pull request by astrojuanlu**
Since Orchest services are supposed to be stateless, recommending PostgreSQL (or any other database) can be misleading to users. They can always set it up themselves, but hopefully this will avoid typical data loss.

## Description

This hides the PostgreSQL service from the list of options.

WIP: Docs

Fixes: #878

## Checklist

- [x] The documentation reflects the changes.
- [x] The PR branch is set up to merge into `dev` instead of `master`.
- [ ] In case I changed one of the services’ `models.py` I have performed the appropriate database
      migrations (refer to `scripts/migration_manager.sh`).
- [ ] In case I changed code in the `orchest-sdk` I followed its [release
      checklist](https://github.com/orchest/orchest/blob/master/orchest-sdk/python/RELEASE-CHECKLIST.md)
- [ ] In case I changed code in the `orchest-cli` I followed its [release
      checklist](https://github.com/orchest/orchest/blob/master/orchest-cli/RELEASE-CHECKLIST.md)
- [ ] I haven't introduced breaking changes that would disrupt existing jobs, i.e. backwards
      compatibility is maintained.
- [ ] In case I changed the dependencies in any `requirements.in` I have run `pip-compile` to update
      the corresponding `requirements.txt`.

### CODE REVIEW

**Comment by astrojuanlu** [comment]
Rendered docs: https://docs.orchest.io/en/stable/fundamentals/services.html (just missing a new screenshot)

**Review by iannbing — APPROVED** [review]
No concerns on the FE side. Yet I'm curious about how we could inform user about this: 

> Since Orchest services are supposed to be stateless

**Comment by astrojuanlu** [comment]
It's mentioned in the first paragraph:

> To ease development, services have a lifetime that spans across the entire [session](https://orchest--1005.org.readthedocs.build/en/1005/fundamentals/glossary.html#interactive-session).

But perhaps it's worth adding a more visible indication.

**Comment by fruttasecca** [comment]
Wouldn't changing the `postgres` service template to make use of the data or project dir mount also solve the issue? I.e. the solution that's proposed in https://github.com/orchest/orchest/issues/878.

**Comment by astrojuanlu** [comment]
That would be another solution yes, but after some discussion we decided against it:

> I think until we have services that don’t share the lifecycle with sessions (eg start and stop with the session, ie in jobs they get killed when the pipeline run ends and for sessions when the session is stopped), we should recommend using external services for stateful/persistent services (like Postgres on RDS or Streamlit apps/(Fast)API endpoints on Heroku/Render/Northflank).

**Comment by fruttasecca** [comment]
Alright sounds good!

**Pull request merged**
