### PR TITLE
Add docs logos for dark and light themes

### PR DESCRIPTION
**Pull request by ncspost**
## Description

Fix our docs logo which doesn't have a transparent bg or adapt to dark theme

CleanShot 2022-08-22 at 13 25 26@2x

## Checklist

- [x] I have manually tested my changes and I am happy with the result.
- [x] The PR branch is set up to merge into `dev` instead of `master`.

### CODE REVIEW

**Comment by ricklamers** [comment]
Nice job! Could you bump logo resolution for retina/high DPI displays? I think at least 298x64, perhaps double that to be on the safe side.

**Comment by astrojuanlu** [comment]
Seeing broken links in the rendered docs:

image

https://orchest--1215.org.readthedocs.build/en/1215/

**Comment by ncspost** [comment]
> Nice job! Could you bump logo resolution for retina/high DPI displays? I think at least 298x64, perhaps double that to be on the safe side.

Done @ricklamers

**Comment by ricklamers** [comment]
@ncspost did you try building docs locally? Wdyt re:@juanlu’s remark?

**Comment by ncspost** [comment]
> @ncspost did you try building docs locally? Wdyt re:@astrojuanlu’s remark?

@ricklamers - dumb question... how do I do that? I just changed the file directly on GH.

**Comment by yannickperrenet** [comment]
@ncspost To build the docs locally take a look at: https://docs.orchest.io/en/stable/development/development_workflow.html#id4

**Comment by ricklamers** [comment]
@astrojuanlu didn't know about the preview URL provided by RTD. Niiceeeee!

**Pull request merged**
