### PR TITLE
Updated login view for Orchest Cloud

### PR DESCRIPTION
**Pull request by ricklamers**
## Description

The new login screen takes into account the new design for when the instance is part of Orchest Cloud.

Furthermore, I've added automatic login redirect if a user is already authenticated.

@fruttasecca @yannickperrenet please double check the security logic.

### Checklist
- [x] I have manually tested the application to make sure the changes don’t cause any downstream issues, which includes making sure `./orchest status --ext` is not reporting failures when Orchest is running.

### CODE REVIEW

**Comment by yannickperrenet** [comment]
image

The font here seems to be different than inside the product? Or am I just seeing things? :grimacing:

**Comment by yannickperrenet** [comment]
I think it is a bit strange that, having AUTH enabled and going to `/login/admin` shows you the regular admin page.

image

**Comment by ricklamers** [comment]
> I think it is a bit strange that, having AUTH enabled and going to `/login/admin` shows you the regular admin page. But this happens only sometimes (other times the path can not be found -- a `401` is returned)... not sure how to trigger it.
> 
> image

This is a valid endpoint as long as you’re authenticated. That’s either when auth is disabled (then all requests are authenticated) or when auth is enabled and you have a valid session cookie.

**Comment by ricklamers** [comment]
> image
> 
> The font here seems to be different than inside the product? Or am I just seeing things? 😬

Should be the same (Inter weights 400 and 600)

**Comment by fruttasecca** [comment]
>But this happens only sometimes (other times the path can not be found -- a 401 is returned)... not sure how to trigger it.

same

**Comment by fruttasecca** [comment]
The page is super nice by he way :+1:

**Comment by fruttasecca** [comment]
One nitpick:
- login as any user
- go back to `http://localhost:8000/login` (don't logout)
- input random username and password
- login

**Comment by ricklamers** [comment]
> go back to http://localhost:8000/login (don't logout)

This would redirect you (unless you use the browser back button). But you already have a valid auth session so the login will just pick up on this and redirect you.

**Comment by fruttasecca** [comment]
>This would redirect you (unless you use the browser back button)

It's not actually redirecting me when I am going directly to the specified URL through the browser. Don't think this is a problem.

**Comment by yannickperrenet** [comment]
> not sure how to trigger it

I can not reproduce in incognito mode so I guess it has something to do with caching.

Otherwise I can do the following:
1. visit localhost:800/login/admin (fails)
2. visit localhost:800/login
3. visit localhost:800/login/admin (works)
4. visit localhost:800/login/admin (fails)

**Pull request merged**
