### PR TITLE
Compare version correctly

### PR DESCRIPTION
**Pull request by yannickperrenet**
## Description

String comparison of versions breaks because we don't use a padding zero for the
patch segment of our CalVer and SemVer versioning scheme.

## Checklist
- [x] Update `useCheckUpdate.tsx` for update dialog
- [X] In case I changed code in the `orchest-sdk` I followed its [release
      checklist](https://github.com/orchest/orchest/blob/master/orchest-sdk/python/RELEASE-CHECKLIST.md)

### CODE REVIEW

**Comment by fruttasecca** [comment]
Should we make use of https://pypi.org/project/packaging/? Comparing versions should be about 2 lines of code

**Comment by astrojuanlu** [comment]
> Should we make use of https://pypi.org/project/packaging/?

+1, see https://packaging.pypa.io/en/latest/version.html

**Comment by yannickperrenet** [comment]
> Should we make use of https://pypi.org/project/packaging/? Comparing versions should be about 2 lines of code with this

Given that it is just one function, I don't think it makes sense to add an additional dependency.

**Review by fruttasecca — APPROVED** [review]
>Given that it is just one function, I don't think it makes sense to add an additional dependency.

lgtm then

**Pull request merged**
